### PR TITLE
Fix registration of empty abstract classes extending godot classes

### LINKED ISSUE #365: Abstract parent classes need to be registered to godot.
Do not know if it is a feature or a bug.

I have this class:
```
import godot.annotation.RegisterClass
import godot.annotation.RegisterFunction
import godot.global.GD

@RegisterClass("Player")
class Player: BaseEntity() {
    @RegisterFunction
    override fun _ready(){
        GD.print("I am the player!")
    }
}
```
If `BaseClass` is not registered to godot (should not be, as it is an abstract class), then the generated code will reference the non-existant `BaseEntityRegistrar`. 
This is also bad, as because that parent is abstract, the generated code is now wrong, as it tries to get its constructor.

### PR DESCRIPTION
**Pull request by chippmann**
Resolves #365.

### CODE REVIEW

File: harness/tests/src/main/kotlin/godot/tests/inheritance/AbstractClassInheritanceEmptyParent.kt [hunk 1]
```diff
@@ -0,0 +1,6 @@
+package godot.tests.inheritance
+
+import godot.KinematicBody
+
+// issue: https://github.com/utopia-rise/godot-kotlin-jvm/issues/365
+abstract class AbstractClassInheritanceEmptyParent: KinematicBody()
```
Comment (raniejade) [inline harness/tests/src/main/kotlin/godot/tests/inheritance/AbstractClassInheritanceEmptyParent.kt:6]: is the missing `@RegisterClass` intentional?

**Review by raniejade — APPROVED** [review]

File: harness/tests/src/main/kotlin/godot/tests/inheritance/AbstractClassInheritanceEmptyParent.kt (hunk 1 above)
Comment (chippmann) [reply harness/tests/src/main/kotlin/godot/tests/inheritance/AbstractClassInheritanceEmptyParent.kt:6]: Yes. Abstract classes don't need to be registered. See: https://godot-kotl.in/en/stable/user-guide/advanced/abstract_classes/

**Review by CedNaru — APPROVED** [review]

**Review by piiertho — APPROVED** [review]
