### PR TITLE
fix: Getter now calls method from parent even if getter starts with is

### LINKED ISSUE #216: `InputEventMouseButton` has no `pressed` property getter
Well, it has, but it looks like this:

```kotlin
open var pressed: Boolean
	  get() {
	    throw UninitializedPropertyAccessException("Cannot access property pressed: has no getter")
	  }
```

### PR DESCRIPTION
**Pull request by piiertho**
Generated getters were not calling parent method if method was starting with `is`.
This resolves #216

### CODE REVIEW

File: kt/api-generator/src/main/kotlin/godot/codegen/generationEntry.kt [hunk 1]
```diff
@@ -35,17 +36,18 @@ fun File.generateApiFrom(jsonSource: File, docsDir: File? = null) {
...
                 property.type,
                 isVirtual = false,
                 hasVarargs = false,
                 arguments = listOf()
             )
             val parentClassAndMethod = tree.getMethodFromAncestor(clazz, method)
             if (parentClassAndMethod != null && !property.hasValidGetter) {
-                val parentMethodName = "get${parentClassAndMethod.first.newName}${property.newName.capitalize()}"
+                val isBoolGetter = property.getter.startsWith("is")
+                val parentMethodName = "${if (isBoolGetter) "is" else "get"}${parentClassAndMethod.first.newName}${property.newName.capitalize()}"
```
Comment (chippmann) [inline kt/api-generator/src/main/kotlin/godot/codegen/generationEntry.kt:48]: I would separate the property name from the parent method call in the getter. Because you share this variable for both property name and parent method call the properties names are quite redundant.
Example (see in the generated files in this PR):
`isFontDistanceField` instead of `isDistanceFieldHint` inside the `Font` class. `Font` in the property name is redundant.
`isInputEventEcho` instead of `isEcho` inside the `InputEvent` class. `InputEvent` in the property name is redundant.

File: kt/godot-library/src/main/kotlin/godot/gen/godot/Font.kt [hunk 2]
```diff
@@ -141,7 +141,7 @@ open class Font : Resource() {
   /**
    *
    */
-  open fun isDistanceFieldHint(): Boolean {
+  open fun isFontDistanceField(): Boolean {
```
Comment (chippmann) [inline kt/godot-library/src/main/kotlin/godot/gen/godot/Font.kt:144]: Weird property name because of comment above

File: kt/godot-library/src/main/kotlin/godot/gen/godot/InputEvent.kt [hunk 3]
```diff
@@ -122,7 +122,7 @@ open class InputEvent : Resource() {
   /**
    * Returns `true` if this input event is an echo event (only for events of type [godot.InputEventKey]).
    */
-  open fun isEcho(): Boolean {
+  open fun isInputEventEcho(): Boolean {
```
Comment (chippmann) [inline kt/godot-library/src/main/kotlin/godot/gen/godot/InputEvent.kt:125]: Same

File: kt/godot-library/src/main/kotlin/godot/gen/godot/InputEvent.kt [hunk 4]
```diff
@@ -131,7 +131,7 @@ open class InputEvent : Resource() {
   /**
    * Returns `true` if this input event is pressed. Not relevant for events of type [godot.InputEventMouseMotion] or [godot.InputEventScreenDrag].
    */
-  open fun isPressed(): Boolean {
+  open fun isInputEventPressed(): Boolean {
```
Comment (chippmann) [inline kt/godot-library/src/main/kotlin/godot/gen/godot/InputEvent.kt:134]: And so on. Will not comment the other appearances :-)

**Review by chippmann — CHANGES_REQUESTED** [review]

File: kt/api-generator/src/main/kotlin/godot/codegen/generationEntry.kt (hunk 1 above)
Comment (piiertho) [reply kt/api-generator/src/main/kotlin/godot/codegen/generationEntry.kt:48]: This redundancy is desired, because if we do not change the name of parent getter we end up with conflicts between getter of properties and get methods from parent in api. 
Is is a particular case where this would not occur. But this happens with variable starting with get :/

Comment (piiertho) [reply kt/api-generator/src/main/kotlin/godot/codegen/generationEntry.kt:48]: @CedNaru gave me a better idea. I'll use @JvmName (which I forgot it exists as I do not write java anymore xD)

**Comment by CedNaru** [comment]
@JvmName should be your friend.

**Review by chippmann — APPROVED** [review]
Yeah with `@JvmName` it's fine now :-)

Edit: hoh `@`JvmName is a user on github xD i guess he'll get's mentioned a lot because of this xD

**Review by CedNaru — APPROVED** [review]
