### PR TITLE
Fix module wizard submodule handling

### LINKED ISSUE #179: [IDEA] Generating a project as a submodule results in putting all files in a root project directory instead of inside the submodule
**Steps:**
```
GIVEN I have a random project opened in IDEA, for example "D:\Repositories\random_project"
AND I click right click on a root project directory name
THEN I click New -> Module
AND I select "Godot Kotlin JVM"
AND I click "Next" on a dialog creation window
AND I make sure that the "Content root" and "Module file location" are a nested directories inside current project, for example: "D:\Repositories\random_project\client-jvm"
THEN I click "Finish"
```

**Expected result:**
All the files created inside "D:\Repositories\random_project\client-jvm"

**Actual result:**
All the project files are not inside "D:\Repositories\random_project\client-jvm", but rather "D:\Repositories\random_project"

### PR DESCRIPTION
**Pull request by chippmann**
Resolves #179

### CODE REVIEW

File: kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/module/GodotModuleBuilder.kt [hunk 1]
```diff
@@ -114,36 +118,86 @@ class GodotModuleBuilder : ModuleBuilder(), ModuleBuilderListener {
...
+                        .let { content ->
+                            if (module.parentProjectAlreadyContainsDependency(wizardContext, "godot-library")) {
+                                content.replace(
+                                    "GODOT_KOTLIN_DEPENDENCY",
+                                    "id(\"com.utopia-rise.godot-kotlin-jvm\")"
+                                )
+                            } else {
+                                content.replace(
+                                    "GODOT_KOTLIN_DEPENDENCY",
+                                    "id(\"com.utopia-rise.godot-kotlin-jvm\") version \"0.1.4-3.2.3\""
```
Comment (CedNaru) [inline kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/module/GodotModuleBuilder.kt:184]: Isn't that error pron to hardcode the version here ? We might forget it when we bump the version?

Comment (chippmann) [reply kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/module/GodotModuleBuilder.kt:184]: I had that once but removed it again because the build props were causing an issue in the ide plugin. Don't remember what. I'll try again

**Review by raniejade — APPROVED** [review]
LGTM pending the removal of the embedded version.

**Review by piiertho — APPROVED** [review]

**Review by CedNaru — APPROVED** [review]
