### PR TITLE
Hotfix/enforce local

### LINKED ISSUE #166: Editor bugs: Grid is missing, incorrect line numbers in scripts
Version: https://github.com/utopia-rise/godot-kotlin-jvm/releases/tag/0.1.4-3.2.3
Platform: Ubuntu 20.04.2 LTS
Editor: godot-kotlin-jvm_editor_x11_.zip

First, I want to say that your project is amazing. I really love Kotlin and the ability to use this language in Godot makes me very happy!

I am trying to work with your build of godot editor and encountering several problems: 

1. Editor grid is missing:
image

2. Incorrect line numbers in all scripts (include GDScript):
image

3. Remote tree of running game also doesn't work. Maybe this log will help:

`
Running: /home/sipaha/Programs/godot/godot.x11.opt.tools.64 --path /home/sipaha/GodotProject --remote-debug 127.0.0.1:6007,000000 --allow_focus_steal_pid 157961 --position 448,240 res://Spatial.tscn
ERROR: to_int: Cannot represent 6007,000000 as integer, provided value is too big.
   At: core/ustring.cpp:1794.
ERROR: connect_to_host: Remote Debugger: Unable to connect. Status: 3.
   At: scene/debugger/script_debugger_remote.cpp:95.
`

I am checked this builds:
1. last release (godot-kotlin-jvm/releases/tag/0.1.4-3.2.3) - problems exist
2. build from sources with kotlin module - problems exists
3. build from same engine sources, but without kotlin module - problems doesn't exists
4. last official release - problems doesn't exists

### LINKED ISSUE #170: no nodes are created in the running instance
When I try to run a test scene, I see that it's running, but nothing is instantiated in the game. The godot logo pops up for a second, then becomes hidden.
Manjaro, java 11.

image
image

### PR DESCRIPTION
**Pull request by piiertho**
This resolves #166 
This resolves #170

### CODE REVIEW

File: src/jni/platforms/jvm_desktop.cpp [hunk 1]
```diff
@@ -38,12 +42,22 @@ namespace jni {
...
         }
 
-        JavaVM* vm;
-        JNIEnv* env;
-        auto result = JvmLoader::get_create_jvm_function()(&vm, (void**) &env, (void*) &args);
+        JavaVM* java_vm{nullptr};
+        JNIEnv* jni_env{nullptr};
+
+#ifndef NO_USE_STDLIB
+        std::locale global;
```
Comment (CedNaru) [inline src/jni/platforms/jvm_desktop.cpp:49]: You just create a new global right? Can't you retrieve the one currently set ?

**Review by chippmann — CHANGES_REQUESTED** [review]

File: src/jni/platforms/jvm_desktop.cpp (hunk 1 above)
Comment (piiertho) [reply src/jni/platforms/jvm_desktop.cpp:49]: From [cpp référence](https://en.cppreference.com/w/cpp/locale/locale/locale) default constructor of `std::local` will retreive global or use `std::local::classic` if global has not been set.

**Review by chippmann — APPROVED** [review]

**Review by CedNaru — APPROVED** [review]

**Review by raniejade — APPROVED** [review]
