### PR TITLE
Move from KSP to classgraph for registration code and initial Scala support

### LINKED ISSUE #773: Type aliases aren't unwrapped when processing property, function, and signal registrations
I'm trying to define type aliases for primitives and Godot types, but I'm running into issues with registered properties/functions/signals.

Version: **0.11.0-4.3**

### Property Registration

I have the following type alias:

```kotlin
typealias SchemaId = String
```

I'm trying to register a property with this type:

```kotlin
@Export
@RegisterProperty
var schemaId: SchemaId = ""
```

But this leads to the following exception during compilation (from KSP):

```
[ksp] <path>: Registered property can only be of type primitive, core type, node type or ref counted
```

Expected behavior: The registration processor recognizes that the `SchemaId` type is actually a `String` type.

### Function Registration

I have the following type alias:

```kotlin
typealias GlobalPosition = Vector2
```

I'm trying to register the following function:

```kotlin
@RegisterFunction
fun changeZone(destinationScene: PackedScene, destinationPosition: GlobalPosition) {
    // ...
}
```

Unfortunately, this leads to the following registration in the class's registrar:

```kotlin
function(MyGame::changeZone, NIL, OBJECT, GLOBALPOSITION, KtFunctionArgument(OBJECT, "godot.PackedScene", "destinationScene"), KtFunctionArgument(GLOBALPOSITION, "mygame.core.GlobalPosition", "destinationPosition"), KtFunctionArgument(NIL, "kotlin.Unit"), KtRpcConfig(RPC_MODE_DISABLED.id.toInt(), false, TRANSFER_MODE_RELIABLE.id.toInt(), 0))
```

The generated code cannot be compiled because `GLOBALPOSITION` doesn't exist.

Expected behavior: The registration processor recognizes that `GlobalPosition` is a `Vector2` and uses this type in the registrar.

### Signal Registration

Taking the same `GlobalPosition` type alias, I'm trying to declare the following signal:

```kotlin
@RegisterSignal
val changeZone by signal2<PackedScene, GlobalPosition>("destinationScene", "destinationGlobalPosition")
```

This results in the following registrar code:

```kotlin
signal(GlobalSignals::changeZone, KtFunctionArgument(OBJECT, "godot.PackedScene", "destinationScene"), KtFunctionArgument(GLOBALPOSITION, "mygame.core.GlobalPosition", "destinationGlobalPosition"))
```

This again fails to compile because `GLOBALPOSITION` doesn't exist.

### PR DESCRIPTION
**Pull request by piiertho**
This moves from KSP to classgraph to generate registration code.  
This also adds initial Scala support to the module.

*edit by @chippmann*: resolves #773

### CODE REVIEW

File: kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/projectExt/configureThirdPartyPlugins.kt [hunk 1]
```diff
@@ -1,20 +1,17 @@
...
 fun Project.configureThirdPartyPlugins() {
     //apply needed third party plugins
-    repositories.google() //add google repository for ksp (kotlin symbol processing
-    pluginManager.apply(KspGradleSubplugin::class.java)
-    pluginManager.apply(IdeaPlugin::class.java) //needed so idea can find and index the generated sources from ksp
-    pluginManager.apply(IdeaExtPlugin::class.java) //needed so idea can find and index the generated sources from ksp
+    pluginManager.apply(IdeaPlugin::class.java) //needed so idea can find and index the generated sources from classgraph
+    pluginManager.apply(IdeaExtPlugin::class.java) //needed so idea can find and index the generated sources from classgraph
     pluginManager.apply(ShadowPlugin::class.java)
+    pluginManager.apply(ScalaPlugin::class.java)
```
Comment (chippmann) [inline kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/projectExt/configureThirdPartyPlugins.kt:14]: I'd rather not add scala support out of the box. I'd rather provide a configuration where scala support can be enabled.

File: kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/projectExt/setupConfigurationsAndCompilations.kt [hunk 2]
```diff
@@ -22,11 +22,14 @@ fun Project.setupConfigurationsAndCompilations() {
             compileOnly("com.utopia-rise:$godotApiArtifactName:${GodotBuildProperties.assembledGodotKotlinJvmVersion}")
             compileOnly("com.utopia-rise:$godotExtensionArtifactName:${GodotBuildProperties.assembledGodotKotlinJvmVersion}")
             compileOnly("com.utopia-rise:godot-kotlin-symbol-processor:${GodotBuildProperties.assembledGodotKotlinJvmVersion}")
+
+            afterEvaluate {
```
Comment (chippmann) [inline kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/projectExt/setupConfigurationsAndCompilations.kt:26]: why after evaluate?
also I'd like to not add it by default

File: kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/classGraphSymbolsProcess.kt [hunk 3]
```diff
@@ -0,0 +1,73 @@
...
+import org.gradle.api.Project
+import org.gradle.api.Task
+import org.gradle.api.tasks.TaskProvider
+import org.jetbrains.kotlin.gradle.dsl.KotlinJvmCompilerOptions
+import org.jetbrains.kotlin.gradle.dsl.KotlinJvmOptions
+import org.jetbrains.kotlin.gradle.plugin.mpp.KotlinWithJavaCompilation
+import java.io.File
+
+fun Project.classGraphSymbolsProcess(
+    classGraphKotlinCompile: KotlinWithJavaCompilation<KotlinJvmOptions, KotlinJvmCompilerOptions>,
```
Comment (chippmann) [inline kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/classGraphSymbolsProcess.kt:16]: KotlinJvmOptions is deprecated

File: kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/classGraphSymbolsProcess.kt [hunk 4]
```diff
@@ -0,0 +1,73 @@
...
+                        godotJvmExtension.isRegistrationFileHierarchyEnabled.get(),
+                        godotJvmExtension.isRegistrationFileGenerationEnabled.getOrElse(true),
+                        layout.buildDirectory.get()
+                            .asFile
+                            .resolve("generated")
+                            .resolve("classgraph")
+                    ),
+                    logger,
+                    classPath
+                )
```
Comment (chippmann) [inline kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/classGraphSymbolsProcess.kt:65]: Please add parameter names. This is hard to read imo

File: kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/initialJavaCompileForClassGraph.kt [hunk 5]
```diff
@@ -0,0 +1,24 @@
...
+import org.gradle.api.tasks.TaskProvider
+import org.gradle.api.tasks.compile.JavaCompile
+
+fun Project.initialJavaCompileForClassGraph(): TaskProvider<JavaCompile> {
+    val mainSourceSet =  project.extensions
+        .getByType(SourceSetContainer::class.java)
+        .getByName("main")
+
+    val classGraphJavaCompile = tasks.register("intitialForClassGraphCompileJava", JavaCompile::class.java) {
+        it.source = mainSourceSet.allJava.asFileTree
```
Comment (chippmann) [inline kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/initialJavaCompileForClassGraph.kt:14]: don't we limit the classgraph to the main source set like this? so adding separate source sets is not possible like this right?

File: kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/initialKotlinCompileForClassGraph.kt [hunk 6]
```diff
@@ -0,0 +1,49 @@
...
+import org.gradle.api.tasks.scala.ScalaCompile
+import org.jetbrains.kotlin.gradle.dsl.KotlinJvmCompilerOptions
+import org.jetbrains.kotlin.gradle.dsl.KotlinJvmOptions
+import org.jetbrains.kotlin.gradle.plugin.mpp.KotlinWithJavaCompilation
+import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
+
+fun Project.initialKotlinCompileForClassGraph(
+    classGraphScalaCompile: TaskProvider<ScalaCompile>,
+    classGraphJavaCompile: TaskProvider<JavaCompile>
+): KotlinWithJavaCompilation<KotlinJvmOptions, KotlinJvmCompilerOptions> {
```
Comment (chippmann) [inline kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/initialKotlinCompileForClassGraph.kt:17]: KotlinJvmOptions is deprecated

File: kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/initialKotlinCompileForClassGraph.kt [hunk 7]
```diff
@@ -0,0 +1,49 @@
...
+    val mainCompilation = kotlinJvmExtension.target.compilations.getByName("main")
+
+    val mainSourceSet =  project.extensions
```
Comment (chippmann) [inline kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/initialKotlinCompileForClassGraph.kt:20]: same here

File: kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/initialScalaCompileForClassGraph.kt [hunk 8]
```diff
@@ -0,0 +1,35 @@
...
+import godot.gradle.projectExt.kotlinJvmExtension
+import org.gradle.api.Project
+import org.gradle.api.tasks.SourceSetContainer
+import org.gradle.api.tasks.TaskProvider
+import org.gradle.api.tasks.scala.ScalaCompile
+
+fun Project.initialScalaCompileForClassGraph(): TaskProvider<ScalaCompile> {
+    val mainCompilation = kotlinJvmExtension.target.compilations.getByName("main")
+
+    val mainSourceSet =  project.extensions
```
Comment (chippmann) [inline kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/initialScalaCompileForClassGraph.kt:12]: and here

File: kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/setupBuildTask.kt [hunk 9]
```diff
@@ -29,6 +29,7 @@ fun Project.setupBuildTask(
                 copyJarTask,
                 packageBootstrapJarTask,
                 packageMainJarTask,
+//                packageMainJarWithClassGraph
```
Comment (chippmann) [inline kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/setupBuildTask.kt:32]: dead code

File: src/script/jvm_script.cpp [hunk 10]
```diff
@@ -59,7 +61,19 @@ bool JvmScript::inherits_script(const Ref<Script>& p_script) const {
...
+    for (const Dictionary& item: ProjectSettings::get_singleton()->get_global_class_list()) {
+        String class_name = item["class"];
+        if (class_name != parent_name) {
+            continue;
+        }
+
+        String script_path = item["path"];
+        return ResourceLoader::load(script_path);
+    }
+
```
Comment (chippmann) [inline src/script/jvm_script.cpp:75]: this needs to be updated. This PR will be merged after 4.4 is released from us so the base branch of this PR can already be the 4.4 update branch imo and this can be fixed already.
After 4.4 is merged into  master, gtihub will change the target branch to master automatically anyways

**Review by chippmann — CHANGES_REQUESTED** [review]
Please also update the documentation accordingly.
Scala should at least be mentioned like java.
IMO we can add the scala specifics later in a separate PR but it is likely that this will be merged and released before that has happened. So I'd at least mention it.

Also: why not directly deleting the ksp implementation with this PR? currently there is no fallback where the user can fallback to the old symbol processor so i see no point in keeping that code around any longer.

File: kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/initialKotlinCompileForClassGraph.kt (hunk 6 above)
Comment (chippmann) [reply kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/initialKotlinCompileForClassGraph.kt:17]: After examination i think we can ignore this deprecation. They still use it internally and it's what we get from the kotlin plugin when creating a compilation.
I think it's deprecated beacause it was initially exposed for configuration by end users and now that configuration is done differently. But i think we can and should still rely on it internally.

File: kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/projectExt/configureThirdPartyPlugins.kt (hunk 1 above)
Comment (piiertho) [reply kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/projectExt/configureThirdPartyPlugins.kt:14]: I don't really know how to do so, since configurations are not resolved before plugins

File: kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/initialJavaCompileForClassGraph.kt (hunk 5 above)
Comment (piiertho) [reply kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/initialJavaCompileForClassGraph.kt:14]: I think you're right. Do you know a better way to do ?

File: kt/entry-generation/godot-class-graph-symbol-processor/src/main/kotlin/godot/annotation/processor/classgraph/extensions/AnnotationExtensions.kt [hunk 11]
```diff
@@ -0,0 +1,174 @@
...
+            }
+
+            val typeDescriptor = parentDeclaration.typeSignature
+
+            require(typeDescriptor is ClassRefTypeSignature)
+
+            require(typeDescriptor.fullyQualifiedClassName == SET) {
+                "Property annotated with EnumFlag should be of type $SET"
+            }
+
```
[the remark this answers is not in the document]
Comment (piiertho) [reply kt/entry-generation/godot-class-graph-symbol-processor/src/main/kotlin/godot/annotation/processor/classgraph/extensions/AnnotationExtensions.kt]: changed it, can you cross check ?

File: kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/projectExt/configureThirdPartyPlugins.kt (hunk 1 above)
Comment (chippmann) [reply kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/projectExt/configureThirdPartyPlugins.kt:14]: I already prepared it in a separate branch to be merged after this one. Will resolve the conversation :-)

File: kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/initialJavaCompileForClassGraph.kt (hunk 5 above)
Comment (chippmann) [reply kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/initialJavaCompileForClassGraph.kt:14]: Also already resolved in the separate branch. will resolve the conversation

File: docs/src/doc/user-guide/signals_and_callables.md [hunk 12]
```diff
@@ -35,6 +35,16 @@ public MyScript extends Node {
 ```
 ///
 
+/// tab | Scala
+```scala
+@RegisterClass
+class MyScript extends Node {
+    @RegisterSignal("reverse")
+    val mySignal: Signal1[Boolean] = Signal1.create(this, "mySignal") // Only one way to do it in Java.
```
Comment (chippmann) [inline docs/src/doc/user-guide/signals_and_callables.md:43]: Typo: in scala

File: docs/src/doc/user-guide/signals_and_callables.md [hunk 13]
```diff
@@ -143,6 +172,33 @@ public class AnotherObject extends Object {
...
+
+@RegisterClass
+class AnotherObject extends Object {
+    @RegisterSignal("reverse")
+    val mySignal: Signal1[Boolean] = Signal1.create(this, "mySignal")
+
+    private val targetObject = new SomeObject()
+
+    public AnotherObject() {
+        // Here are 3 different ways to connect a signal to a registered method. The method reference syntax is not implemented for Java.
```
Comment (chippmann) [inline docs/src/doc/user-guide/signals_and_callables.md:193]: For scala

File: kt/entry-generation/godot-class-graph-symbol-processor/src/main/kotlin/godot/annotation/processor/classgraph/extensions/AnnotationExtensions.kt [hunk 14]
```diff
@@ -0,0 +1,181 @@
...
+            sync = getSyncMode(),
+            transferMode = getTransferMode(),
+            transferChannel = parameterValues.getValue("transferChannel") as Int,
+            symbolProcessorSource = this
+        )
+        "godot.annotation.GodotBaseType" -> GodotBaseTypeAnnotation(this) // is internal
+        EnumFlag::class.java.name -> {
+            if (parentDeclaration !is FieldInfo) {
+                ErrorsDatabase.add(
+                    "EnumFlag annotation should be placed on property."
```
Comment (chippmann) [inline kt/entry-generation/godot-class-graph-symbol-processor/src/main/kotlin/godot/annotation/processor/classgraph/extensions/AnnotationExtensions.kt:70]: I'd add where this error occurred. If you have multiple such error's then it's hard to find. Maybe add the declaration to the error db as well and assemble the final error message when you print them?

Comment (chippmann) [reply kt/entry-generation/godot-class-graph-symbol-processor/src/main/kotlin/godot/annotation/processor/classgraph/extensions/AnnotationExtensions.kt:70]: There are similar cases at other places

File: kt/entry-generation/godot-class-graph-symbol-processor/src/main/kotlin/godot/annotation/processor/classgraph/extensions/ClassExtentions.kt [hunk 15]
```diff
@@ -0,0 +1,178 @@
...
+            fieldInfo.hasAnnotation(RegisterSignal::class.java, this)
+        }
+        .map { it.mapFieldToRegisteredSignal(settings, this) }
+
+    val shouldBeRegistered = shouldBeRegistered(methods, fields, signals)
+
+    return if (shouldBeRegistered) {
+        if (!constructorInfo.any { it.isPublic && it.parameterInfo.isEmpty() }) {
+            ErrorsDatabase.add(
+                "You should provide a default constructor for class $fqName"
```
Comment (chippmann) [inline kt/entry-generation/godot-class-graph-symbol-processor/src/main/kotlin/godot/annotation/processor/classgraph/extensions/ClassExtentions.kt:50]: Like here. This is good and can be found even with many errors

Comment (chippmann) [reply kt/entry-generation/godot-class-graph-symbol-processor/src/main/kotlin/godot/annotation/processor/classgraph/extensions/ClassExtentions.kt:50]: This can conversation can just be resolved when read :-)

**Review by chippmann — CHANGES_REQUESTED** [review]

File: kt/entry-generation/godot-class-graph-symbol-processor/src/main/kotlin/godot/annotation/processor/classgraph/extensions/AnnotationExtensions.kt (hunk 11 above)
[the remark this answers is not in the document]
Comment (chippmann) [reply kt/entry-generation/godot-class-graph-symbol-processor/src/main/kotlin/godot/annotation/processor/classgraph/extensions/AnnotationExtensions.kt]: Looks good. Some remarks on some of the error reports but i opened a separate discussion for it

**Review by chippmann — APPROVED** [review]
Very nice work!

I would not merge this in master though atm. This together with other big upcoming changes makes it harder to create bugfix releases in the meantime until these bigger tasks are finished.
Hence i propose to reintroduce a develop branch until these bigger changes are done.

**Review by CedNaru — APPROVED** [review]
Took the liberty to create a develop branch and redirected the PR to it.
Otherwise, looks good to me for a first version. We'll see for more vicious potential bugs once we start using it for real.
I would also delete the ksp processor directory, but it can be done at a later point.
