### PR TITLE
Fix resource property type hint

### LINKED ISSUE #394: Exported property type is ignored in Inspector tab
There are too many options so you have to scroll a lot.

Equivalent GDScript code (e.g. `export var test: Texture`) shows only inherited types.

export_type_issue

### PR DESCRIPTION
**Pull request by chippmann**
Fixes #394

This fixes the type hints for resource types.
The issue we were having was two fold:
- For once we did not check the supertypes recursively to detect whether the property was a resource type (in fact the relevant type is `Reference`). We also had that problem for list types. I fixed it there too as well.
- Secondly, since we initially implemented this, two new type hints were added, which meant that the ordinal was not correct anymore. By adding the missing typehints, the ordinal we send to the cpp code is correct again. **Note:** We should investigate if we can either automatically generate these typehint enums, or automatically test whether they are still correct. But I think this is out of the scope for this fix.

### CODE REVIEW

File: kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/ext/TypeExtensions.kt [hunk 1]
```diff
@@ -54,14 +54,13 @@ fun Type.toTypeName(): TypeName = ClassName(
 
 fun Type.isCompatibleList(): Boolean = when (fqName) {
     "godot.core.GodotArray", "godot.core.VariantArray" -> true
```
Comment (CedNaru) [inline kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/ext/TypeExtensions.kt:56]: I think "godot.core.GodotArray" is not even in the codebase anymore. There was a time when we had 2 different array classes, but it was removed a long time ago.

File: kt/godot-library/src/main/kotlin/godot/core/Functions.kt [hunk 2]
```diff
@@ -17,8 +17,10 @@ enum class PropertyHint {
     FLAGS, ///< hint_text= "flag1,flag2,etc" (as bit flags)
     LAYERS_2D_RENDER,
     LAYERS_2D_PHYSICS,
+    LAYERS_2D_NAVIGATION,
```
Comment (CedNaru) [inline kt/godot-library/src/main/kotlin/godot/core/Functions.kt:20]: Before we had to copy multiple enums in the godot library because the generated code was in a different module but now that everything is together, wouldn't that be better to directly use the one available in gen/ ?

Comment (chippmann) [reply kt/godot-library/src/main/kotlin/godot/core/Functions.kt:20]: I agree. As discussed on Discord I will look into this and file a separate PR.

**Review by CedNaru — APPROVED** [review]

**Review by CedNaru — APPROVED** [review]

**Review by piiertho — APPROVED** [review]

**Comment by piiertho** [comment]
Did not see but we seem to have a problem in our tests on array

**Comment by chippmann** [comment]
> Did not see but we seem to have a problem in our tests on array

WDYM? I don't see anything in the actions in this PR?
